### ISSUE TITLE
getLastBidForCanvas should include also canvasId

### ISSUE THREAD

**Issue by krisu-pl** [TheMindhouse/cryptocanvas-solidity#6]
I have one model for `Bid` from `getLastBidForCanvas` and `BidPosted` event. Could we make them consistent, meaning `getLastBidForCanvas` should have also `canvasId` as the first field?

**Comment by k-misztal** [comment]
Done.

Now function declaration looks like this now: `function getLastBidForCanvas(uint32 _canvasId) external view returns (uint32 canvasId, address bidder, uint amount, uint finishTime)`
